plugins {
    id 'java'
}

group 'org.springframework'
version '5.2.7.BUILD-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.junit.jupiter:junit-jupiter:5.9.2'
    compile(project(":spring-context"))
    compile("org.aspectj:aspectjweaver")
}
